/* ═══════════════════════════════════════════════════════
   GROUND STATION MKA-1 — MISSION REGISTRY
   ═══════════════════════════════════════════════════════ */

export const profile = {
  name: "Moe Kyaw Aung",
  nameMM: "မိုးကျော်အောင်",
  title: "Senior Android Developer",
  full: "Senior Android & Full-Stack Developer",
  location: "Tachileik, Myanmar ↔ Bangkok, Thailand",
  email: "moekyawaung@programmer.net",
  phone: "+95 9 889 000 889",
  secondPhone: "+959 666 000 050",
  github: "https://github.com/Dev-moe-kyawaung",
  linkedin: "https://www.linkedin.com/in/moe-kyaw-aung-2653093a1",
  gravatar: "https://gravatar.com/moekyawaung2026",
  avatar: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778527878/IMG_20260430_053105_uef0yr.png",
  aboutImg: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778763531/MKA_12_iv8kpm.webp",
  philosophy: "Code with culture. Build with purpose.",
  availability: "Open to work",
  languages: "Burmese · English · Kotlin",
  building: "MoekyawTranslator — AI Translation App",
};

export type Metric = { value: string; label: string };

export type Mission = {
  id: string; desig: string; name: string; payloadType: string;
  icon: string; color: string;
  orbit: "LEO" | "MEO" | "GEO" | "SSO" | "HEO";
  altitude: string; inclination: string; period: string;
  status: string; launched: string;
  role: string; year: string;
  summary: string; problem: string; approach: string[]; solution: string; impact: string;
  stack: string[]; telemetry: string;
  metrics: Metric[];
  users: number; usersLabel: string;
  image: string; github: string; demo: string;
  snippet: string;
  featured?: boolean;
};

const gh = (r: string) => `https://github.com/${r}`;
const live = "https://moekyawaung-tech.github.io/";

export const missions: Mission[] = [
  {
    id: "pos", desig: "MKA-01", name: "POS Ultimate Pro Max",
    payloadType: "Merchant Command Module", icon: "POS", color: "#00f0ff",
    orbit: "GEO", altitude: "35,786 km", inclination: "0.0°", period: "23h 56m",
    status: "NOMINAL", launched: "2024-03-30",
    role: "Founder & Lead Architect", year: "2024",
    summary: "Offline-first retail infrastructure running real commerce across Myanmar and Thailand. Room is the ground truth; sync is a reconciler, never the authority.",
    problem: "Border merchants trade MMK and THB on networks that fail daily. Sales must commit instantly, receipts print, and nightly reconciliation balances to the last unit — on 2GB-RAM hardware.",
    approach: [
      "Room as single source of truth; every sale commits locally first",
      "WorkManager queue with idempotent replay and server-acked resolution",
      "Dual-currency ledger in fixed-point arithmetic — no float money",
      "Hilt-scoped feature modules so receipts, inventory, and reporting ship independently",
    ],
    solution: "A multi-module Compose app over an MVI core with an encrypted local ledger, background sync that survives days of outage, and a cloud replica that is always eventually consistent — never authoritative.",
    impact: "Outages stopped being business events. Sales continue offline and reconcile cleanly on reconnect, and new features roll out store-by-store instead of fleet-wide.",
    stack: ["Kotlin", "Compose", "Hilt", "Room", "WorkManager", "Firebase", "GitHub Actions"],
    telemetry: "1,200 live stores · 99.98% crash-free",
    metrics: [
      { value: "1,200", label: "stores live" },
      { value: "99.98%", label: "crash-free" },
      { value: "68%", label: "faster builds" },
      { value: "2", label: "currencies" },
    ],
    users: 1200, usersLabel: "live stores",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778763531/MKA_3_zqrhhr.webp",
    github: gh("moekyawaung-tech/POS-Ultimate-Pro-Max"), demo: live,
    snippet: "// POS Ultimate — checkout, offline-first\nsuspend fun checkout(sale: Sale): Receipt = with(store) {\n    val local = insert(sale)            // local truth\n    syncQueue.enqueue(local.id)         // WorkManager\n    printer.print(local)                // instant\n}",
    featured: true,
  },
  {
    id: "social", desig: "MKA-02", name: "Social Dashboard",
    payloadType: "Telemetry Analytics Array", icon: "SOC", color: "#5ce8b6",
    orbit: "LEO", altitude: "540 km", inclination: "53.0°", period: "95m",
    status: "NOMINAL", launched: "2025-02-11",
    role: "Lead Android Engineer", year: "2025",
    summary: "Five disconnected social channels unified into one decision-ready stream. Every metric is a Flow: debounced at the edge, cached locally, rendered through a single reducer.",
    problem: "Teams made calls from stale screenshots stitched across five platforms. Nobody trusted the numbers, and by the time a trend was visible it was already gone.",
    approach: [
      "MVI reducer over StateFlow — every screen renders one immutable state",
      "WebSocket streams debounced into Room so the dashboard survives reconnects",
      "Multi-tenant theming and role-based views from a shared design system",
      "Feature flags for incremental analytics rollouts without release trains",
    ],
    solution: "A realtime telemetry surface where every metric is a Flow: debounced at the edge, cached locally, rendered through a single reducer. The UI is a pure function of one trusted state.",
    impact: "Decisions now ride sub-second data. New metric views ship in days instead of sprints, and uptime holds through traffic spikes.",
    stack: ["Kotlin", "Compose", "MVI", "Flow", "WebSocket", "Firebase", "Room"],
    telemetry: "50,000+ MAU · 99.95% uptime",
    metrics: [
      { value: "1.2M", label: "users" },
      { value: "99.95%", label: "uptime" },
      { value: "900ms", label: "p95 latency" },
    ],
    users: 1200000, usersLabel: "users reached",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778747388/image-1_1_khsx9s.png",
    github: gh("moekyawaung-tech/social-dashboard"), demo: live,
    snippet: "// Social Dashboard — one state, one reducer\nval state: StateFlow<DashboardState> = combine(\n    feedRepo.stream(),\n    analytics.flow(),\n) { feed, analytics -> DashboardState(feed, analytics) }\n    .debounce(180)\n    .stateIn(scope, Eagerly, Empty)",
    featured: true,
  },
  {
    id: "translator", desig: "MKA-03", name: "MoekyawTranslator",
    payloadType: "On-Device AI Payload", icon: "AI", color: "#ffcc00",
    orbit: "MEO", altitude: "20,200 km", inclination: "55.0°", period: "12h",
    status: "DEVELOPING", launched: "2026-01-15",
    role: "Founder & Engineer", year: "2026",
    summary: "Burmese ↔ English translation that routes between a Claude API path and a quantized on-device TFLite path — the user never sees the seam.",
    problem: "Translation for Burmese speakers fails where it matters most: low coverage, low-end devices, and distrust of sending conversations to servers.",
    approach: [
      "Two inference paths — Claude API for quality, quantized TFLite for the edge",
      "A connectivity-aware router picks the path per request and degrades silently on timeout",
      "Conversation history stays in encrypted Room storage by default",
    ],
    solution: "A hybrid inference engine: cloud-quality translation when the network allows, on-device translation when it doesn't — with the user never seeing the seam between them.",
    impact: "Marginal on-device cost is effectively zero — which is what makes regional-language AI viable. 12K joined the waitlist before beta.",
    stack: ["Kotlin", "Compose", "Claude API", "TFLite", "Room", "EncryptedStore"],
    telemetry: "12K waitlist · ~300ms edge latency",
    metrics: [
      { value: "12K", label: "waitlist" },
      { value: "2", label: "inference paths" },
      { value: "300ms", label: "edge latency" },
    ],
    users: 12000, usersLabel: "waitlist",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795856/copilot_image_1778795675037_heh9xk.png",
    github: profile.github, demo: "https://moekyawaung.lovable.app",
    snippet: "// MoekyawTranslator — hybrid inference\nsuspend fun translate(text: String): Translation {\n    return if (router.prefersCloud(text))\n        claudePath.translate(text)   // quality\n    else\n        tflitePath.translate(text)   // privacy + offline\n}",
    featured: true,
  },
  {
    id: "video", desig: "MKA-04", name: "Video Player Pro",
    payloadType: "Imaging Downlink Package", icon: "VID", color: "#ffcc00",
    orbit: "LEO", altitude: "590 km", inclination: "42.0°", period: "96m",
    status: "DOWNLINKING", launched: "2024-11-15",
    role: "Lead Android Engineer", year: "2024",
    summary: "One playback state machine around ExoPlayer/Media3. Gestures, PiP, and subtitles can't fight the playback loop because they never touch the codec directly.",
    problem: "Playback had to feel identical on a flagship and on a budget handset at a border market — stalls and dropped frames are the moments users blame the product for.",
    approach: [
      "One playback state machine around ExoPlayer / Media3 — the UI never talks to the codec directly",
      "HLS adaptive bitrate with pre-buffer tuned for high-latency networks",
      "Gesture zones for brightness, volume, and seek with hysteresis to kill accidental drags",
      "PiP, subtitle parsing, and a storage-pressure-aware offline cache",
    ],
    solution: "A thin Compose shell over a hardened Media3 core: every event flows through one reducer, so gestures, PiP, and subtitles can't fight the playback loop.",
    impact: "Session completion rose; the zero-dropped-frame release bar held across every device tier.",
    stack: ["Kotlin", "ExoPlayer", "Media3", "HLS", "Compose", "Room"],
    telemetry: "200K+ sessions · zero dropped frames",
    metrics: [
      { value: "820K", label: "users" },
      { value: "4.8★", label: "store rating" },
      { value: "+35%", label: "completion lift" },
    ],
    users: 820000, usersLabel: "active users",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778747384/image-1_f6zlmk.jpg",
    github: gh("moekyawaung-tech/video-player"), demo: live,
    snippet: "// Video Player Pro — single state machine\nwhen (val event = events.receive()) {\n    is Seek   -> player.seekTo(event.ms)\n    is Buffer-> state = State.Buffering\n    is Ready  -> state = State.Playing\n    else      -> state = state.reduce(event)\n}",
    featured: true,
  },
  {
    id: "lens", desig: "MKA-05", name: "Lens Lite",
    payloadType: "Optical Survey Package", icon: "OCR", color: "#bd5cff",
    orbit: "SSO", altitude: "830 km", inclination: "98.7°", period: "101m",
    status: "BETA", launched: "2025-06-20",
    role: "Creator & Engineer", year: "2025",
    summary: "Capture, OCR, classify, and file — entirely on the phone, in under a second. Nothing leaves the device, which turned privacy into the growth story.",
    problem: "The camera is the fastest input only if processing is private and immediate. Cloud OCR broke both promises.",
    approach: [
      "CameraX capture pipeline with ML Kit OCR running fully on-device",
      "A local classifier sorts document types before anything is stored",
      "Minimal state machine keeps capture → extract → organize under three taps",
      "All extracted text lands in encrypted Room storage",
    ],
    solution: "An on-device vision pipeline: capture, OCR, classify, and file — entirely on the phone, in under a second, with nothing leaving the device.",
    impact: "38K monthly active users turned paper into searchable notes with zero cloud dependency — the privacy story became the growth story.",
    stack: ["Kotlin", "CameraX", "ML Kit", "TFLite", "Compose", "Room"],
    telemetry: "38K MAU · 0 cloud uploads",
    metrics: [
      { value: "38K", label: "MAU" },
      { value: "3", label: "taps to file" },
      { value: "0", label: "cloud uploads" },
    ],
    users: 38000, usersLabel: "monthly active",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795829/copilot_image_1778795000722_okryxj.png",
    github: gh("moekyawaung-tech/Lens-lite"), demo: live,
    snippet: "// Lens Lite — on-device OCR pipeline\nval capture = camera.take()\nval text = mlkit.extract(capture)   // local\nval doc = classifier.sort(text)\nroom.save(doc)                      // encrypted",
    featured: true,
  },
  {
    id: "job", desig: "MKA-06", name: "Job Portal App",
    payloadType: "Workforce Relay", icon: "JOB", color: "#5ce8b6",
    orbit: "LEO", altitude: "410 km", inclination: "64.2°", period: "92m",
    status: "NOMINAL", launched: "2023-08-14",
    role: "Creator & Engineer", year: "2023",
    summary: "Regional talent matched to remote work, with applications that survive the exact connectivity gaps the users live with daily.",
    problem: "Skilled people in border towns had no clean path to remote work; listings vanished in chat groups within hours.",
    approach: [
      "Search, filters, notifications, and profiles as independent feature modules over Firebase",
      "Paging 3 with offline-tolerant placeholders",
      "Push fan-out tuned so a new post reaches matched seekers within seconds",
    ],
    solution: "A job marketplace where matching happens server-side but the experience is offline-tolerant: listings cache, applications queue, and nothing is lost to a dropped connection.",
    impact: "320K job seekers exploring roles without losing applications to dropped connections.",
    stack: ["Kotlin", "Firebase", "Compose", "Paging 3", "FCM"],
    telemetry: "320K seekers · 3s post-to-notify",
    metrics: [{ value: "320K", label: "seekers" }, { value: "4.6★", label: "rating" }, { value: "3s", label: "post-to-notify" }],
    users: 320000, usersLabel: "job seekers",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795800/2024119_18_syk2ou.jpg",
    github: gh("moekyawaung-tech/Job-Portal-App"), demo: live,
    snippet: "// Job Portal — applications survive offline\nval application = applications.queue(local)\n// paging placeholders while the\n// network is unreachable",
  },
  {
    id: "admin", desig: "MKA-07", name: "Admin Dashboard",
    payloadType: "Fleet Telemetry Hub", icon: "ADM", color: "#ffcc00",
    orbit: "HEO", altitude: "120,000 km", inclination: "45.0°", period: "24h",
    status: "SECURE", launched: "2024-01-19",
    role: "Lead Engineer", year: "2024",
    summary: "Role-based operational control with audit-grade visibility. Data and permissions live in the same place.",
    problem: "Operations teams saw the system through disconnected exports; by the time a number was questioned it was a day old.",
    approach: [
      "RBAC with audit logging at the data layer",
      "Chart streams over shared API adapters",
      "Reusable UI modules for multi-tenant views",
    ],
    solution: "One control surface with role-based views, live charts, and an audit trail that answers 'who changed what' without a spreadsheet.",
    impact: "Incident triage dropped from hours to minutes because the data and the permissions live in the same place.",
    stack: ["Kotlin", "Compose", "RBAC", "REST", "Charts"],
    telemetry: "220K operators · 100% actions audited",
    metrics: [{ value: "220K", label: "operators" }, { value: "100%", label: "audited" }],
    users: 220000, usersLabel: "operators",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795822/preview_dzhqvv.webp",
    github: gh("moekyawaung-tech/Advance-POS-Version"), demo: live,
    snippet: "// Admin — every action is auditable\n@Audit(action = \"CONFIG_UPDATE\")\nfun updateConfig(change: Change) {\n    policy.ensure(role, Scope.CONFIG)\n    store.apply(change)\n}",
  },
  {
    id: "stock", desig: "MKA-08", name: "Stock Market",
    payloadType: "Market Flux Sensor", icon: "MKT", color: "#00f0ff",
    orbit: "LEO", altitude: "620 km", inclination: "28.5°", period: "97m",
    status: "ACQUIRING", launched: "2024-04-22",
    role: "Creator & Engineer", year: "2024",
    summary: "Market data without the casino energy — conflated channels so only the newest tick renders, alerts as a first-class feature.",
    problem: "Fast-moving market data usually ships as noise that encourages tapping, not thinking.",
    approach: [
      "Conflated channels so only the newest tick renders",
      "Canvas candlesticks drawn off the main thread",
      "Alerts as a first-class feature, not an afterthought",
    ],
    solution: "A calm observation layer: debounced ticks, custom canvas rendering, and alerts that fire on conditions instead of attention.",
    impact: "260K watchlists with a render pipeline that never drops frames during market open.",
    stack: ["Kotlin", "Canvas", "WebSocket", "Flow", "Room"],
    telemetry: "260K watchlists · 200ms tick latency",
    metrics: [{ value: "260K", label: "watchlists" }, { value: "200ms", label: "tick latency" }],
    users: 260000, usersLabel: "watchlists",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795847/copilot_image_1778795115579_acfm5j.png",
    github: gh("moekyawaung-tech/crypto"), demo: live,
    snippet: "// Stock — only the newest tick survives\nchannel.receiveAsFlow()\n    .conflate()\n    .collect { tick -> chart.draw(tick) }",
  },
  {
    id: "games", desig: "MKA-09", name: "Game Collection",
    payloadType: "Recreation Sub-Deck", icon: "GAM", color: "#bd5cff",
    orbit: "LEO", altitude: "410 km", inclination: "64.2°", period: "92m",
    status: "NOMINAL", launched: "2023-05-08",
    role: "Creator & Engineer", year: "2023",
    summary: "A fixed-timestep engine where new games are content, not rebuilds — one loop, one renderer, one score system.",
    problem: "Each mini-game was a throwaway experiment until players asked where the last one went.",
    approach: [
      "Fixed-timestep game loop shared across titles",
      "Canvas renderer with sprite batching",
      "Room-backed leaderboard and audio nodes",
    ],
    solution: "A lightweight engine where new games are content, not rebuilds — one loop, one renderer, one score system.",
    impact: "2.1M plays at a stable 60 FPS; new titles ship in days.",
    stack: ["Kotlin", "Canvas", "Room", "Web Audio"],
    telemetry: "2.1M plays · 60 FPS locked",
    metrics: [{ value: "2.1M", label: "plays" }, { value: "60", label: "fps locked" }],
    users: 2100000, usersLabel: "plays",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795800/2024119_12_sqhcat.jpg",
    github: gh("moekyawaung-tech/game-collection"), demo: live,
    snippet: "// Game Collection — fixed timestep\nwhile (running) {\n    accumulator += frame\n    while (accumulator >= STEP) {\n        world.step(STEP)\n        accumulator -= STEP\n    }\n    renderer.draw(world)\n}",
  },
  {
    id: "music", desig: "MKA-10", name: "Music Player",
    payloadType: "Acoustic DSP Package", icon: "MUS", color: "#ffcc00",
    orbit: "LEO", altitude: "505 km", inclination: "33.0°", period: "94m",
    status: "NOMINAL", launched: "2023-05-27",
    role: "Creator & Engineer", year: "2023",
    summary: "Gapless playback where the spectrum, the queue, and the hardware keys all observe one source of truth.",
    problem: "Playback gaps and dead zones ruin commutes.",
    approach: [
      "Audio-node graph with FFT spectrum analysis",
      "Playlist state machine with gapless handoff",
      "MediaSession integration for lock-screen and hardware keys",
    ],
    solution: "A player built around one state machine: the spectrum, the queue, and the hardware keys all observe the same source of truth.",
    impact: "410K listeners with gapless playback and a visualizer that runs at full rate on budget hardware.",
    stack: ["Kotlin", "ExoPlayer", "FFT", "MediaSession"],
    telemetry: "410K listeners · 0ms gap",
    metrics: [{ value: "410K", label: "listeners" }, { value: "0", label: "gap between tracks" }],
    users: 410000, usersLabel: "listeners",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795856/copilot_image_1778794626112_ega7kk.png",
    github: gh("moekyawaung-tech/video-player"), demo: live,
    snippet: "// Music — one source of truth\nmediaController\n    .events()\n    .onEach { event -> queue.reduce(event) }\n    .launchIn(scope)",
  },
  {
    id: "chat", desig: "MKA-11", name: "Chat App",
    payloadType: "Encrypted Comms Relay", icon: "CHT", color: "#5ce8b6",
    orbit: "GEO", altitude: "35,786 km", inclination: "0.1°", period: "23h 56m",
    status: "ENCRYPTED", launched: "2023-06-14",
    role: "Creator & Engineer", year: "2023",
    summary: "Every message lands in a local outbox first and earns a receipt on delivery — sent, delivered, read.",
    problem: "At the border, a message sent is not a message delivered.",
    approach: [
      "Offline queue with delivery receipts",
      "Encrypted payloads end-to-end",
      "Presence and typing signals over the same socket",
    ],
    solution: "A socket-based messenger where every message lands in a local outbox first and earns a receipt on delivery.",
    impact: "1M+ messages relayed with delivery guarantees users can see — sent, delivered, read.",
    stack: ["Kotlin", "Socket.IO", "Room", "Encryption"],
    telemetry: "1M+ messages · E2EE enforced",
    metrics: [{ value: "1M+", label: "messages" }, { value: "100%", label: "receipts" }],
    users: 1000000, usersLabel: "messages relayed",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795859/copilot_image_1778794430377_n7xlmz.png",
    github: gh("moekyawaung-tech/pwa-app"), demo: live,
    snippet: "// Chat — outbox first, receipt second\nval message = outbox.send(payload)\nsocket.onAck(message.id) { receipt ->\n    outbox.markDelivered(message.id)\n}",
  },
  {
    id: "worldcup", desig: "MKA-12", name: "World Cup Portal",
    payloadType: "Event Telemetry Feed", icon: "WCP", color: "#ffcc00",
    orbit: "MEO", altitude: "18,400 km", inclination: "45.0°", period: "10h",
    status: "STREAMING", launched: "2022-06-30",
    role: "Creator & Engineer", year: "2022",
    summary: "One calm surface for fixtures, live scores, and brackets — recomputed in real time, readable at a glance.",
    problem: "During a World Cup everyone has scores; nobody has a calm place to follow a bracket.",
    approach: [
      "SSE streams for live match events",
      "Bracket recomputation on every goal",
      "Push alerts tuned to the matches you follow",
    ],
    solution: "One surface for fixtures, live scores, and brackets — recomputed in realtime and readable at a glance.",
    impact: "690K followers through the tournament with sub-second goal alerts.",
    stack: ["Kotlin", "SSE", "Push", "Compose"],
    telemetry: "690K followers · 1s goal alert",
    metrics: [{ value: "690K", label: "followers" }, { value: "1s", label: "goal alert" }],
    users: 690000, usersLabel: "followers",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795799/2024119_20_b94fen.jpg",
    github: gh("moekyawaung-tech/thailand-travel"), demo: live,
    snippet: "// World Cup — bracket recompute\nonGoal(match) {\n    bracket.apply(match)\n    if (user.follows(match))\n        push.notify(user, match)\n}",
  },
  {
    id: "ecom", desig: "MKA-13", name: "E-Commerce Suite",
    payloadType: "Commerce Transaction Bus", icon: "ECM", color: "#00f0ff",
    orbit: "GEO", altitude: "35,786 km", inclination: "0.0°", period: "23h 56m",
    status: "NOMINAL", launched: "2023-11-02",
    role: "Creator & Engineer", year: "2023",
    summary: "A checkout flow where the cart survives anything and the payment call is safe to retry.",
    problem: "Cart abandonment wasn't a persuasion problem — it was a connectivity problem.",
    approach: [
      "Optimistic cart with local persistence",
      "Idempotent payment calls with retry",
      "Receipt generation offline-first",
    ],
    solution: "A checkout flow where the cart survives anything and the payment call is safe to retry.",
    impact: "480K shoppers with measurably fewer abandoned carts on 2G-class connections.",
    stack: ["Kotlin", "Compose", "Room", "Stripe"],
    telemetry: "480K shoppers · 99.9% success",
    metrics: [{ value: "480K", label: "shoppers" }, { value: "+22%", label: "cart recovery" }],
    users: 480000, usersLabel: "shoppers",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778763532/MKA_11_jbijtv.webp",
    github: gh("moekyawaung-tech/POS-Full-Version"), demo: live,
    snippet: "// E-commerce — safe to retry\nval cart = cart.restore()\nval intent = payment.prepare(cart)\n// idempotency key on every retry",
  },
  {
    id: "money", desig: "MKA-14", name: "Money Tracker",
    payloadType: "Encrypted Ledger Vault", icon: "MTR", color: "#bd5cff",
    orbit: "SSO", altitude: "780 km", inclination: "98.6°", period: "100m",
    status: "SEALED", launched: "2024-07-18",
    role: "Creator & Engineer", year: "2023",
    summary: "A fully local dual-currency ledger — encrypted at rest, impossible to leak, because it never connects.",
    problem: "People between two currencies had no budget tool that didn't force a choice — or send their spending to a server.",
    approach: [
      "Encrypted Room storage — zero network permission",
      "Fixed-point MMK/THB conversions",
      "Budget thresholds with quiet alerts",
    ],
    solution: "A fully local ledger: encrypted at rest, dual-currency by design, and impossible to leak because it never connects.",
    impact: "410K budgeters tracking across MMK and THB with a privacy story that is simply: there is no server.",
    stack: ["Kotlin", "Room", "Encryption", "Charts"],
    telemetry: "410K ledgers · zero data egress",
    metrics: [{ value: "410K", label: "budgeters" }, { value: "2", label: "currencies" }],
    users: 410000, usersLabel: "budgeters",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795856/copilot_image_1778795000722_eo96gj.png",
    github: gh("moekyawaung-tech/Daily-planner-app"), demo: live,
    snippet: "// Money Tracker — no server to hack\n// (zero network permission in the manifest)\nval tx = ledger.record(\n    FixedPoint(amount, MMK)\n)",
  },
  {
    id: "weather", desig: "MKA-15", name: "Weather Radar",
    payloadType: "Atmospheric Sounder", icon: "WX", color: "#5ce8b6",
    orbit: "SSO", altitude: "830 km", inclination: "98.7°", period: "101m",
    status: "SCANNING", launched: "2024-08-09",
    role: "Creator & Engineer", year: "2023",
    summary: "The answer is the first thing you see, and severe weather finds you before you look.",
    problem: "For border traders, weather decides the day — most apps bury the answer under chrome.",
    approach: [
      "Cached forecasts with background refresh",
      "Location-aware severe-weather alerts",
      "Animated canvas conditions layer",
    ],
    solution: "A forecast surface where the answer is the first thing you see and severe weather finds you before you look.",
    impact: "690K daily checks with alerts that arrive ahead of monsoon fronts.",
    stack: ["Kotlin", "Compose", "Retrofit", "WorkManager"],
    telemetry: "75K forecast polls · 30min alert lead",
    metrics: [{ value: "690K", label: "daily checks" }, { value: "30min", label: "alert lead" }],
    users: 690000, usersLabel: "daily checks",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795801/MKA_22_felevo.webp",
    github: gh("moekyawaung-tech/Weather-app"), demo: live,
    snippet: "// Weather — answer first\nval current = cache.latest()\nwork.refresh(30.minutes)\nif (current.severe) alert.localPush(current)",
  },
  {
    id: "legend", desig: "MKA-16", name: "LEGEND! Fleet",
    payloadType: "Primary Mission Bus", icon: "LGD", color: "#ffcc00",
    orbit: "GEO", altitude: "100,000 km", inclination: "0.0°", period: "23h 56m",
    status: "FLAGSHIP", launched: "2025-03-30",
    role: "Founder & Architect", year: "2026",
    summary: "Sixteen products sharing one spine: design system, navigation contracts, analytics, and account services.",
    problem: "Sixteen products risk becoming sixteen debts without shared infrastructure.",
    approach: [
      "Shared design system and navigation contracts",
      "Common analytics and account services",
      "Per-product feature modules over a shared core",
    ],
    solution: "A super-app pattern where each product is a module, and the ecosystem is the product.",
    impact: "5.2M total users; new products launch on shared infrastructure in weeks.",
    stack: ["Kotlin", "Compose", "Firebase", "Design System", "CI/CD"],
    telemetry: "5.2M total users · 16 products",
    metrics: [{ value: "5.2M", label: "total users" }, { value: "16", label: "products" }],
    users: 5200000, usersLabel: "total users",
    image: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778747391/image_mplr5r.png",
    github: profile.github, demo: live,
    snippet: "// LEGEND! — one spine, sixteen products\ninclude(\":feature:pos\")\ninclude(\":feature:social\")\ninclude(\":feature:translator\")\n// ...each builds on :core:*",
  },
];

/* ── skills ── */
export const skills = [
  { code: "S-1", group: "Android", note: "the craft itself", items: ["Kotlin", "Jetpack Compose", "Coroutines & Flow", "Room", "WorkManager", "CameraX", "Media3 / ExoPlayer", "Material 3"] },
  { code: "S-2", group: "Architecture", note: "systems that hold", items: ["Clean Architecture", "MVI / MVVM", "Multi-module", "Hilt / Dagger", "Repository pattern", "Offline-first"] },
  { code: "S-3", group: "Backend & APIs", note: "services behind the UI", items: ["Firebase (Auth/Firestore/FCM)", "REST", "Retrofit / OkHttp", "Node.js", "PostgreSQL", "Python"] },
  { code: "S-4", group: "AI / ML", note: "intelligence at the edge", items: ["TensorFlow Lite", "Claude API", "ML Kit", "On-device inference", "Quantization"] },
  { code: "S-5", group: "Security", note: "trust as a feature", items: ["Keystore / AES-256", "Certificate pinning", "TLS 1.3", "OWASP MASVS", "R8 / obfuscation", "Biometrics"] },
  { code: "S-6", group: "DevOps / CI-CD", note: "shipping without drama", items: ["GitHub Actions", "Fastlane", "Gradle", "Docker", "Staged rollouts", "Screenshot testing", "JUnit / MockK / Espresso"] },
  { code: "S-7", group: "Tools", note: "the daily instruments", items: ["Android Studio", "Git", "Figma", "VS Code", "Jira", "Baseline Profiles"] },
];

/* ── experience ── */
export const experience = [
  { year: "2026", title: "Independent — Senior Android & Full-Stack Developer", org: "MKA Studio · Tachileik ⇄ Bangkok", text: "Architecture reviews, founding-engineer engagements, and MoekyawTranslator: regional-language AI that runs on-device. Mentoring engineers through the Compose transition.", tags: ["Android", "Architecture", "Mentoring", "AI/ML"], ach: "OPEN TO SENIOR & FOUNDING ROLES" },
  { year: "2024", title: "Technical Founder — POS Ultimate", org: "Merchant OS · Myanmar & Thailand", text: "Took a merchant OS from prototype to 1,200 live stores across two countries. Owned the dual-currency offline ledger, sync engine, and release pipeline end-to-end.", tags: ["Startup", "Android", "Architecture", "Performance"], ach: "1,200 STORES · 2 COUNTRIES" },
  { year: "2023", title: "Delivery & Performance Lead", org: "Independent", text: "Built release machinery: GitHub Actions, Fastlane signing, screenshot testing, staged rollouts, 90%+ coverage gates. Cut cold-start P90 to 620ms and reduced OOM crashes through bitmap lifecycle and memory-budget work.", tags: ["CI/CD", "Performance", "Memory"], ach: "COLD START 620MS · SHIP CYCLE → DAYS" },
  { year: "2022", title: "Architecture Lead", org: "Android portfolio-wide", text: "Adopted Clean Architecture, Hilt, and Flow across the portfolio. Drove the multi-module split that cut build times 68% and delivered 6-second incremental builds on 80+ modules.", tags: ["Architecture", "Android", "Performance"], ach: "80+ MODULES · 6S INCREMENTAL BUILDS" },
  { year: "2021", title: "Compose Migration", org: "Three production apps", text: "Moved production surfaces from XML to Jetpack Compose with MVI state handling and a shared design system. Mentored teammates with pairing sessions and review templates.", tags: ["Android", "Mentoring", "Architecture"], ach: "3 APPS MIGRATED · 0 REGRESSIONS" },
  { year: "2019", title: "First Ship", org: "Play Store", text: "Java and XML. First Android app reached the Play Store — and taught everything a first production app teaches about lifecycle, crashes, and real users.", tags: ["Android"], ach: "FIRST PRODUCTION RELEASE" },
];

/* ── achievements ── */
export const verifiedCertificates = [
  { name: "C Programming", cat: "Programming", id: "1720080366600", date: "Jul 4, 2024" },
  { name: "C++ Systems Mastery", cat: "Programming", id: "1720080489120", date: "Jul 5, 2024" },
  { name: "Java Advanced Enterprise", cat: "Programming", id: "1720080512300", date: "Jul 6, 2024" },
  { name: "Python Scripting & Core", cat: "Programming", id: "1720080598100", date: "Jul 7, 2024" },
  { name: "Kotlin Mobile Development", cat: "Mobile", id: "1720080612400", date: "Jul 8, 2024" },
  { name: "Android Architecture Components", cat: "Mobile", id: "1720080645100", date: "Jul 9, 2024" },
  { name: "Jetpack Compose UI Framework", cat: "Mobile", id: "1720080698200", date: "Jul 10, 2024" },
  { name: "Flutter & Dart Mobile Engine", cat: "Mobile", id: "1720080723100", date: "Jul 11, 2024" },
  { name: "React Native Cross-Platform", cat: "Mobile", id: "1720080789400", date: "Jul 12, 2024" },
  { name: "React.js Web Engineering", cat: "Web Dev", id: "1720080812300", date: "Jul 13, 2024" },
  { name: "Vue.js Framework Architecture", cat: "Web Dev", id: "1720080845600", date: "Jul 14, 2024" },
  { name: "Angular Enterprise Systems", cat: "Web Dev", id: "1720080891200", date: "Jul 15, 2024" },
  { name: "Node.js & Express REST APIs", cat: "Web Dev", id: "1720080923400", date: "Jul 16, 2024" },
  { name: "HTML5 & CSS3 Master", cat: "Web Dev", id: "1720080967800", date: "Jul 17, 2024" },
  { name: "Tailwind CSS UI Styling", cat: "Web Dev", id: "1720080998100", date: "Jul 18, 2024" },
  { name: "TypeScript Systems Engineering", cat: "Web Dev", id: "1720081034500", date: "Jul 19, 2024" },
  { name: "Firebase Backend Suite", cat: "Databases", id: "1720081078900", date: "Jul 20, 2024" },
  { name: "PostgreSQL Relational DB", cat: "Databases", id: "1720081112300", date: "Jul 21, 2024" },
  { name: "MongoDB NoSQL Architecture", cat: "Databases", id: "1720081145600", date: "Jul 22, 2024" },
  { name: "Redis In-Memory Cache", cat: "Databases", id: "1720081198200", date: "Jul 23, 2024" },
  { name: "SQL Query Optimization", cat: "Databases", id: "1720081234500", date: "Jul 24, 2024" },
  { name: "Room Local DB for Android", cat: "Databases", id: "1720081278900", date: "Jul 25, 2024" },
  { name: "Machine Learning Fundamentals", cat: "AI / ML", id: "1720081312300", date: "Jul 26, 2024" },
  { name: "TensorFlow Lite On-Device ML", cat: "AI / ML", id: "1720081345600", date: "Jul 27, 2024" },
  { name: "Deep Learning & Neural Networks", cat: "AI / ML", id: "1720081398200", date: "Jul 28, 2024" },
  { name: "Natural Language Processing NLP", cat: "AI / ML", id: "1720081434500", date: "Jul 29, 2024" },
  { name: "Claude API LLM Integration", cat: "AI / ML", id: "1720081512300", date: "Jul 31, 2024" },
  { name: "Ethical Hacking & Pen Testing", cat: "Security", id: "1720081545600", date: "Aug 1, 2024" },
  { name: "Cybersecurity Kali Linux Protocols", cat: "Security", id: "1720081598200", date: "Aug 2, 2024" },
  { name: "GitHub Actions CI/CD Pipeline", cat: "Security", id: "1720081634500", date: "Aug 3, 2024" },
  { name: "Docker Space Containerization", cat: "Security", id: "1720081678900", date: "Aug 4, 2024" },
  { name: "Azure DevOps Enterprise Pipelines", cat: "Security", id: "1720081712300", date: "Aug 5, 2024" },
  { name: "Blockchain Architecture", cat: "Blockchain", id: "1720081798200", date: "Aug 7, 2024" },
  { name: "Smart Contract Development", cat: "Blockchain", id: "1720081834500", date: "Aug 8, 2024" },
  { name: "Clean Architecture Pattern Design", cat: "Software Eng.", id: "1720081878900", date: "Aug 9, 2024" },
  { name: "SOLID Principles in OOP", cat: "Software Eng.", id: "1720081912300", date: "Aug 10, 2024" },
  { name: "Design Patterns Gang of Four", cat: "Software Eng.", id: "1720081945600", date: "Aug 11, 2024" },
  { name: "Data Structures & Algorithms", cat: "Software Eng.", id: "1720081998200", date: "Aug 12, 2024" },
  { name: "Startup MVP Engineering Lab", cat: "Business", id: "1720082034500", date: "Aug 13, 2024" },
  { name: "Agile Scrum Leadership", cat: "Business", id: "1720082078900", date: "Aug 14, 2024" }
];

export const achievements = {
  certifications: {
    total: "82+",
    note: "Programming Hub — verified, dated, and categorized across nine domains. Google Developers Launchpad alumnus.",
    groups: [
      { name: "Programming", count: 13 }, { name: "Web Dev", count: 13 }, { name: "Mobile", count: 7 },
      { name: "Databases", count: 6 }, { name: "AI / ML", count: 11 }, { name: "Security", count: 10 },
      { name: "Blockchain", count: 4 }, { name: "Software Eng.", count: 7 }, { name: "Business", count: 11 },
    ],
  },
  openSource: {
    total: "20",
    note: "Public repositories and 30+ GitHub organizations covering Android, security tooling, AI experiments, and web deployments.",
    stats: [
      { end: 20, suffix: "", label: "public repos" },
      { end: 30, suffix: "+", label: "GitHub orgs" },
      { end: 43, suffix: "", label: "linked accounts" },
    ],
  },
  launches: {
    total: "1,200",
    note: "Merchant stores live on POS Ultimate, plus 20 consumer products shipped to production across two countries.",
    stats: [
      { end: 1200, suffix: "", label: "stores live" },
      { end: 20, suffix: "", label: "products shipped" },
      { end: 10, suffix: "M+", label: "users reached" },
    ],
  },
  milestones: [
    "10M+ lifetime users reached across the portfolio",
    "99.98% crash-free sessions sustained in production",
    "68% build-time reduction after multi-module split",
    "Cold-start P90 optimized to 620ms",
    "82+ verified certifications, Google Developers Launchpad",
    "1,200 merchant stores running on POS Ultimate",
  ],
};

/* ── network ── */
export const githubAccounts = [
  "Dev-moe-kyawaung", "moekyawaung-tech", "Moekyawaung-cyber", "moekyawaung-china", "moekyawaung-developer",
  "moekyawaung-microsoft", "moekyawaung-google", "moekyawaung-bangkok", "moekyawaung-micro", "moekyaw-aung-mm",
  "moekyawaung-mk", "moekyaw-developer", "Moekyawaung-mm", "moekyawaung-hack", "moekyawaung-graduate",
  "Moekyawaung-Linux", "Moekyawaung-coder", "moekyawaung-designer", "Moekyawaung2026", "moekyawaung-web",
  "MoeKyawAung-code", "moekyawaung-creator", "moekyawaung-webdeveloper", "Moekyawaung-co", "moekyawaung-edu",
  "moekyawaung-senior", "Moekyawaung-Development", "Moe-KyawAung", "moekyawaung-vivov30pro", "moekyawaungmka",
  "moekyawaungmka2032-boop", "moekyawaungmka2034-coder", "moekyaw-dev-mm", "moekyawaung-dev", "happy-cv-creator"
];

export const lovableWebApps = [
  { name: "Happy CV Creator", url: "https://happy-cv-creator.lovable.app" },
  { name: "MKA Bio Hub", url: "https://moekyawaungmybio.lovable.app/" },
  { name: "The CV Palette", url: "https://the-cv-palette.lovable.app" },
  { name: "URL Shortener Pro", url: "https://moekyaw-url.lovable.app" },
  { name: "Dev Profile 2026", url: "https://moekyawaung-dev.lovable.app" },
  { name: "Main Interstellar Hub", url: "https://moe-kyaw-aung.lovable.app" },
  { name: "MKA Mobile Suite", url: "https://moekyawaungmka.lovable.app" },
  { name: "CV Beacon System", url: "https://cv-beacon.lovable.app/" },
  { name: "Persuasion Hub", url: "https://profile-persuasion-hub.lovable.app" },
  { name: "Friendly Haven Cloud", url: "https://friendly-haven-io.lovable.app" },
  { name: "Joy Codify Life", url: "https://joy-codify-life.lovable.app/" },
  { name: "Spark Coach AI", url: "https://spark-coach-create.lovable.app" },
  { name: "Color Code Chronicles", url: "https://color-code-chronicles.lovable.app" },
  { name: "Pixel Perfect Snap", url: "https://pixel-perfect-snap-39.lovable.app" },
  { name: "App Skill Gallery", url: "https://app-skill-gallery.lovable.app" },
  { name: "Myanmar Hub", url: "https://moekyawaung-myanmar.lovable.app" }
];

export const mediaShowcase = [
  { type: "image", url: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778763531/MKA_12_iv8kpm.webp", title: "Engineering Command Setup", tag: "HARDWARE" },
  { type: "image", url: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778747388/image-1_1_khsx9s.png", title: "Architecture Flowchart Ingest", tag: "SCHEMATIC" },
  { type: "image", url: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778763531/MKA_3_zqrhhr.webp", title: "POS Merchant Hardware Rig", tag: "RETAIL" },
  { type: "image", url: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778763532/MKA_11_jbijtv.webp", title: "Multi-Module Workspace", tag: "WORKSPACE" },
  { type: "image", url: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795799/2024119_20_b94fen.jpg", title: "Tachileik Lab Testing", tag: "LAB" },
  { type: "image", url: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778795801/MKA_22_felevo.webp", title: "Bangkok Studio Rig", tag: "STUDIO" },
  { type: "image", url: "https://res.cloudinary.com/dye5qpwii/image/upload/v1778763536/preview_ls5ptn.webp", title: "App Collection Matrix", tag: "DEPLOYMENT" },
  { type: "video", url: "https://res.cloudinary.com/dye5qpwii/video/upload/v1779052711/Javier_Black-Dark-Ring.mp4", title: "3D Dark Ring Kinetic", tag: "3D MOTION" }
];

export const socials = [
  { name: "GitHub", url: "https://github.com/Dev-moe-kyawaung" },
  { name: "LinkedIn", url: "https://www.linkedin.com/in/moe-kyaw-aung-2653093a1" },
  { name: "YouTube", url: "https://www.youtube.com/channel/UCuTXUguZb4xjeL2nX8WJG" },
  { name: "Gravatar", url: "https://gravatar.com/moekyawaung2026" },
  { name: "Bluesky", url: "https://bsky.app/profile/moekyawaung96.bsky.social" },
  { name: "Tumblr", url: "https://www.tumblr.com/moekyawaung" },
  { name: "Flickr", url: "https://www.flickr.com/people/204037451@N06" },
  { name: "Vimeo", url: "https://vimeo.com/user252414232" },
  { name: "Slack", url: "https://moekyawaung.slack.com/" },
  { name: "PayPal", url: "https://www.paypal.com/paypalme/my/profile" },
  { name: "Strikingly", url: "http://moekyawaung2026.strikingly.com" },
  { name: "Lovable", url: "https://moekyawaung.lovable.app" },
];

export const emails = [
  "moekyawaung@programmer.net", "moekyawaung@collector.org", "moekyawaung@technologist.com",
  "moekyawaung@techie.com", "moekyawaung@graphic-designer.com", "moekyawaung@cybergal.com",
  "moekyawaung@webname.com", "moekyawaung@hackermail.com", "moekyawaung@graduate.org",
  "moekyawaung@engineer.com", "moekyawaung@asia.com", "moekyawaung@contractor.net",
  "moekyawaung@linuxmail.org", "moekyawaung@usa.com", "moekyawaung@europe.com",
  "moekyawaung@mail.com", "moekyawaung@iname.com", "moekyawaung@socialogist.com",
  "moekyawaung@secretary.net", "moekyawaung@publicist.com",
];

export const credStrip = [
  { end: 10, suffix: "M+", label: "users reached" },
  { end: 20, suffix: "", label: "products shipped" },
  { end: 99.98, suffix: "%", decimals: 2, label: "crash-free" },
  { end: 82, suffix: "+", label: "certifications" },
];

export const logcatLines = [
  { lvl: "I", tag: "GroundStation", msg: "MKA-1 · boot sequence started" },
  { lvl: "D", tag: "DishArray", msg: "azimuth 284.7° · elevation 41.2° locked" },
  { lvl: "I", tag: "Constellation", msg: "16 assets acquired · all tracking nominal" },
  { lvl: "D", tag: "Telemetry", msg: "uplink throughput 84.2 Mb/s · stable" },
  { lvl: "I", tag: "MissionLog", msg: "POS Ultimate in GEO · 1,200 stores synced" },
  { lvl: "W", tag: "Signal", msg: "minor fade detected on MKA-12 · compensated" },
  { lvl: "I", tag: "System", msg: "all stations nominal — ready for visitors." },
];
